### PR TITLE
fix: report Megaphone errors to Sentry

### LINKED ISSUE #118: Notify sentry on MegaphoneUpdater failures
Currently we write to debug log when MegaphoneUpdater attempts fail, with a TODO to notify sentry.

With debug logs being hidden by default on prod, we should begin notifying sentry about issues communicating with megaphone instead.

For the sake of diagnosing such issues: https://bugzilla.mozilla.org/show_bug.cgi?id=1585042

### PR DESCRIPTION
**Pull request by leplatrem**
fixes #118 

I wanted to use `capture_error(&error)` but didn't manage to convert errors types from  `autopush_common::errors` :grin:

### CODE REVIEW

File: autopush/src/server/mod.rs [hunk 1]
```diff
@@ -639,9 +639,12 @@ impl Future for MegaphoneUpdater {
                             }
                         }
                         Ok(Async::NotReady) => return Ok(Async::NotReady),
-                        Err(_) => {
-                            // TODO: Flag sentry that we can't poll megaphone API
-                            debug!("Failed to get response, queue again");
+                        Err(error) => {
+                            error!("Failed to get response, queue again {:?}", error);
+                            capture_message(
```
Comment (pjenvey) [inline autopush/src/server/mod.rs]: Sentry also has a `capture_error_chain` that might work (though I've never tried it..)

**Comment by jrconlin** [comment]
Going to merge this as is. 

@leplatrem I don't know if there is a way to test it locally. We can open up another issue later if we decide that `capture_error_chain` is a better approach.

**Comment by pjenvey** [comment]
In the past my sentry "test" has been running a local listening netcat alongside a SENTRY_DSN=http://foo:bar@localhost:9999/etc :)
