### PR TITLE
fix: Drop unknown FCM users

### LINKED ISSUE #173: Drop user routing information if bridge reports 404/410 or similar error
If the bridge system reports a user is no longer registered or found, we should drop that user from our routing table. 

Companion to:

https://github.com/mozilla-services/autopush/issues/1414

### PR DESCRIPTION
**Pull request by Mcat12**
Major changes:
- If FCM says the user does not exist (404, [docs]), then we drop the user from the router table.
- `DbClient` is now abstracted via a trait and can be mocked with `MockDbClient`. [Mocking library documentation][mockall].

Closes #173 

[docs]: https://firebase.google.com/docs/reference/fcm/rest/v1/ErrorCode
[mockall]: https://docs.rs/mockall/0.7.1/mockall

### CODE REVIEW

**Comment by jrconlin** [comment]
Heh, kinda burying the lede here that this also wraps in DbClient mocking.

File: autoendpoint/src/db/client.rs [hunk 1]
```diff
@@ -95,6 +104,32 @@ impl DbClientImpl {
...
+            }
+            Err(e) => return Err(e.into()),
+        };
+
+        let status = output
+            .table
+            .and_then(|table| table.table_status)
+            .ok_or(DbError::TableStatusUnknown)?;
+
+        Ok(["CREATING", "UPDATING", "ACTIVE"].contains(&status.as_str()))
```
Comment (jrconlin) [inline autoendpoint/src/db/client.rs:131]: nit: I know that this will probably always be upper case, but I wonder if it might be good to force status to upper case to avoid any future issues.
