### PR TITLE
bug: Do not return status 200 for router messages

### LINKED ISSUE #800: Noncompliant Push Response
Hello,

We have been seeing a lot (10s of thousands) of `200 OK` response codes from sending push messages to firefox users. Here's an example response with the location header obfuscated.

```
"Response { status: 200, version: HTTP/1.1, headers: {"server": "nginx", "date": "Mon, 18 Nov 2024 19:11:00 GMT", "content-length": "0", "ttl": "259200", "vary": "Origin, Access-Control-Request-Method, Access-Control-Request-Headers", "location": "https://updates.push.services.mozilla.com/m/<snip>", "strict-transport-security": "max-age=31536000", "via": "1.1 google", "alt-svc": "h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000"}, body: Body(Empty) }"
```

Based on the response headers, it seems that nginx might be rewriting the response code.

cc @chamons

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-4512)

### PR DESCRIPTION
**Pull request by jrconlin**
Closes #800

### CODE REVIEW

File: autoendpoint/src/routers/mod.rs [hunk 1]
```diff
@@ -50,7 +50,7 @@ impl RouterResponse {
     /// Build a successful (200 OK) router response
```
Comment (chamons) [inline autoendpoint/src/routers/mod.rs:50]:
```suggestion
    /// Build a successful (201 CREATED) router response
```

**Review by pjenvey — CHANGES_REQUESTED** [review]
Can you please also correct the [accompanying docs](https://mozilla-services.github.io/autopush-rs/http.html#calls) while you're at it?

It mentions both 202 and 200 response codes, neither of which are correct after https://github.com/mozilla-services/autopush/pull/1446

**Review by pjenvey — APPROVED** [review]
